name: medal-reactivator
branding:
  icon: "cast"
  color: "blue"
description: Reactivate your bilibili medal
inputs:
  cookies:
    description: Your bilibili account cookies
    required: true
  roomids:
    description: list of liveroom's roomids(eg. 216676,216676)
    required: false
    default: "all"
  ignore:
    description: list of liveroom's roomids that you want to ignore
    required: false
    default: "0"
runs:
  using: composite
  steps:
  - name: Running...
    run: echo "::group::Running..."
    shell: bash
  - name: setup python
    uses: actions/setup-python@v5
    with:
      python-version: 3.9
      cache: 'pip'
  - name: Install requirement
    run: pip install -r $GITHUB_ACTION_PATH/requirements.txt
    shell: bash
  - name: Update gist
    run: python $GITHUB_ACTION_PATH/reactivate.py
    env:
      cookies: ${{ inputs.cookies }}
      roomids: ${{ inputs.roomids }}
      ignore: ${{ inputs.ignore }}
    shell: bash
  - run: echo "::endgroup::"
    shell: bash